CREATE TABLE PessoaJuridica(
	Codigo INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(MAX) NOT NULL,
	Email VARCHAR(MAX) NOT NULL,
	[Site] VARCHAR(MAX) NULL,
	Cnpj VARCHAR(14) NOT NULL,
	InscricaoEstadual VARCHAR(11) NOT NULL,
	InscricaoMunicipal VARCHAR(11) NOT NULL,
	NomeFantasia VARCHAR(MAX) NOT NULL,
	DataInclusao DATETIME NULL DEFAULT(GETDATE()),
	CONSTRAINT PK_PessoaJuridica PRIMARY KEY (Codigo ASC)
)
GO