CREATE TABLE Funcionario(
	Codigo INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(MAX) NOT NULL,
	Email VARCHAR(MAX) NOT NULL,
	[Site] VARCHAR(MAX) NULL,
	Matricula VARCHAR(14) NOT NULL,
	[Login] VARCHAR(MAX) NOT NULL,
	Senha VARCHAR(MAX) NOT NULL,
	DataContratacao DATETIME NULL,
	DataInclusao DATETIME NULL DEFAULT(GETDATE()),
	CONSTRAINT PK_Funcionario PRIMARY KEY (Codigo ASC)
)
GO